# -*- coding: utf-8 -*-
"""case_study1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15YACkAAXa4b5cIYJBkB45zusATKa84Of

This dataset has funding information of the Indian startups from January 2015 to August 2017.

Feature Details :
SNo - Serial number.

Date - Date of funding in format DD/MM/YYYY.

StartupName - Name of the startup which got funded.

IndustryVertical - Industry to which the startup belongs.

SubVertical - Sub-category of the industry type.

CityLocation - City which the startup is based out of.

InvestorsName - Name of the investors involved in the funding round.

InvestmentType - Either Private Equity or Seed Funding.

AmountInUSD - Funding Amount in USD.

Remarks - Other information, if any.

Insights -
Find out what type of startups are getting funded in the last few years?

Who are the important investors?

What are the hot fields that get a lot of funding these days?
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("startup_funding.csv")
#print(df.dtypes)
#print(df["Amount in USD"].apply(type).value_counts())

df["Date"] = df["Date"].str[-4:]
df["Date"] = df["Date"].replace("/015","2015")
df = df.groupby('Date').size()

year_No_dict = df.to_dict()
print(year_No_dict)
year=[]
fundings=[]
for k,v in year_No_dict.items():
  fundings.append(v)
  year.append(k)
  print(k,v)

plt.plot(year,fundings)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("startup_funding.csv")
df=df.dropna(subset=["CityLocation"])
def seperate_city(c):
  return c.split("/")[0].strip()

df['CityLocation']=df["CityLocation"].apply(seperate_city)
df[df["CityLocation"] == "bangalore"] = "Bangalore"
df[df["CityLocation"] == "Delhi"] = "New Delhi"
df = df.groupby(["CityLocation"]).size()
df = df.nlargest(10)

cities = df.to_dict()

city =[]
count =[]
for k,v in cities.items():
  city.append(k)
  count.append(v)
  print(k,v)


plt.pie(count,labels=city)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('startup_funding.csv',encoding = 'utf-8')
df.dropna(subset=["CityLocation"],inplace=True)
def separateCity(city):
    return city.split('/')[0].strip()
df['CityLocation'] = df['CityLocation'].apply(separateCity)
df['CityLocation'].replace("Delhi","New Delhi",inplace = True)
df['CityLocation'].replace("bangalore","Bangalore",inplace = True)
df['AmountInUSD'] = df['AmountInUSD'].str.replace(",","").astype(float)

df = df.groupby('CityLocation')['AmountInUSD'].sum()
df = df.sort_values(ascending = False)[0:10]
city = df.index
amount = df.values
explode = [0.2,0.2,0.2,0.2,0.1,0.1,0.2,0.2,0.2,0.2]
plt.pie(amount,labels = city,autopct='%0.2f',counterclock=False,startangle=90,explode =explode,radius=1.5)
plt.show()

percent = np.true_divide(amount,amount.sum())*100
for i in range(len(city)):
    print(city[i],format(percent[i],'0.2f'))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('startup_funding.csv',encoding = 'utf-8')
df.dropna(subset=["CityLocation"],inplace=True)
def separateCity(city):
    return city.split('/')[0].strip()
df['CityLocation'] = df['CityLocation'].apply(separateCity)
df['CityLocation'].replace("Delhi","New Delhi",inplace = True)
df['CityLocation'].replace("bangalore","Bangalore",inplace = True)
df['AmountInUSD'] = df['AmountInUSD'].str.replace(",","").astype(float)

top_cities = df.groupby('CityLocation')['AmountInUSD'].sum().nlargest(10)
amount =top_cities.values
city =top_cities.index
percentages = (top_cities/top_cities.sum())*100

explode = [0.2,0.2,0.2,0.2,0.1,0.1,0.2,0.2,0.2,0.2]
plt.pie(amount,labels = city,autopct='%0.2f',counterclock=False,startangle=90,explode =explode,radius=1.5)
plt.show()

for c,p in percentages.items():
  print(f"{c} {p:.2f}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('startup_funding.csv',encoding = 'utf-8')
df = df.dropna(subset=["InvestmentType"])


df['AmountInUSD'] = df['AmountInUSD'].apply(lambda x: float(str(x).replace(",","")))
df['InvestmentType'] = df['InvestmentType'].replace(['Crowd funding','PrivateEquity','SeedFunding'],['Crowd Funding','Private Equity','Seed Funding'])
inves_types = df.groupby("InvestmentType")["AmountInUSD"].sum().nlargest(10)
per_cent = (inves_types/inves_types.sum())*100
i = inves_types.index
p = inves_types.values
for k,v in per_cent.items():
  print(f"{k} {v:.2f}")
plt.pie(p,labels=i)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('startup_funding.csv',encoding = 'utf-8')
df = df.dropna(subset=["InvestmentType"])


df['AmountInUSD'] = df['AmountInUSD'].apply(lambda x: float(str(x).replace(",","")))
df['IndustryVertical'] = df['IndustryVertical'].replace(['eCommerce','ECommerce','ecommerce'],['Ecommerce','Ecommerce','Ecommerce'])
inves_types = df.groupby("IndustryVertical")["AmountInUSD"].sum().nlargest(10)
per_cent = (inves_types/inves_types.sum())*100
"""i = inves_types.index
p = inves_types.values
plt.pie(p,labels=i)
plt.show()"""
for k,v in per_cent.items():
  print(f"{k} {v:.2f}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('startup_funding.csv',encoding = 'utf-8')
df = df.dropna(subset=["InvestorsName"])


splitted =df["InvestorsName"].str.split(",",expand=True)
new_df = splitted.stack().reset_index(drop=True)
counts =new_df.value_counts()
print(counts)

import csv
import numpy as np
import matplotlib.pyplot as plt
with open("startup_funding.csv") as f:
  r=csv.DictReader(f)
  investors=[]
  for i in r:
    if not ("undisclosed" in i["InvestorsName"]) or ("Undisclosed" in i["InvestorsName"]):
      for j in i["InvestorsName"].split(","):
        investors.append(j.strip())
  dic ={}
  for i in investors:
    if i in dic:
      dic[i] +=1
    else:
      dic[i] = 1

  max_invest = max(dic,key=dic.get)
  max_investments = dic[max_invest]
  print(max_invest,max_investments)